/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./src/**/*.{js,jsx,ts,tsx}", "./public/index.html"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-tertiary": "#ffffff",
        "on-surface-variant": "#3c4a42",
        "inverse-on-surface": "#eaf1ff",
        "primary-fixed": "#6ffbbe",
        "surface-tint": "#006c49",
        "surface-container-lowest": "#ffffff",
        "on-primary-fixed": "#002113",
        "on-surface": "#121c2a",
        "surface-container-highest": "#d9e3f6",
        "on-error-container": "#93000a",
        "secondary-fixed-dim": "#95d3ba",
        error: "#ba1a1a",
        "surface-container-low": "#eff4ff",
        "surface-dim": "#d0dbed",
        primary: "#006c49",
        "error-container": "#ffdad6",
        "on-tertiary-fixed": "#2a1700",
        "secondary-container": "#adedd3",
        "on-secondary": "#ffffff",
        "on-background": "#121c2a",
        "on-tertiary-fixed-variant": "#653e00",
        "primary-fixed-dim": "#4edea3",
        "tertiary-container": "#e29100",
        surface: "#f8f9ff",
        "on-error": "#ffffff",
        "primary-container": "#10b981",
        "on-tertiary-container": "#523200",
        "surface-container-high": "#dee9fc",
        "on-secondary-fixed-variant": "#0b513d",
        tertiary: "#855300",
        "outline-variant": "#bbcabf",
        "surface-bright": "#f8f9ff",
        "surface-container": "#e6eeff",
        "secondary-fixed": "#b0f0d6",
        background: "#f8f9ff",
        secondary: "#2b6954",
        "on-secondary-fixed": "#002117",
        "inverse-primary": "#4edea3",
        "inverse-surface": "#27313f",
        "on-primary-fixed-variant": "#005236",
        "tertiary-fixed": "#ffddb8",
        "on-secondary-container": "#306d58",
        "on-primary-container": "#00422b",
        "tertiary-fixed-dim": "#ffb95f",
        "surface-variant": "#d9e3f6",
        "on-primary": "#ffffff",
        outline: "#6c7a71",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        xl: "80px",
        "container-max": "1280px",
        md: "24px",
        lg: "48px",
        sm: "12px",
        gutter: "24px",
        xs: "4px",
        base: "8px",
      },
      fontFamily: {
        "headline-md": ["Manrope"],
        "body-md": ["Manrope"],
        "headline-lg": ["Manrope"],
        "body-lg": ["Manrope"],
        "label-bold": ["Inter"],
        "body-sm": ["Manrope"],
        "headline-xl": ["Manrope"],
      },
      fontSize: {
        "headline-md": ["24px", { lineHeight: "1.3", fontWeight: "700" }],
        "body-md": ["16px", { lineHeight: "1.5", fontWeight: "400" }],
        "headline-lg": [
          "32px",
          { lineHeight: "1.25", letterSpacing: "-0.01em", fontWeight: "700" },
        ],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "label-bold": [
          "12px",
          { lineHeight: "1", letterSpacing: "0.05em", fontWeight: "700" },
        ],
        "body-sm": ["14px", { lineHeight: "1.5", fontWeight: "400" }],
        "headline-xl": [
          "48px",
          { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "800" },
        ],
      },
    },
  },
  plugins: [],
};
